### ISSUE TITLE
Error installing libraries on Jetson Orin AGX running Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by LoicBoileau** [DreamVu/PAL-SDK#29]
Hi,

I have been trying to install your library to be able to use your camera on my Jetson Orin agx devkit. However, I am not able to install correctly all the packages. In fact, those 5 packages cant seem to work : Errors were encountered while processing:
 opencv-dvu
 lut-pal
 miscellaneous-pal
 engines-pal
 pal

I have joined the complete log for this command: 
[install_pal.log](https://github.com/DreamVu/PAL-SDK/files/13340368/install_pal.log)

Could you help me figure out how to setup those libraries correctly ? Thanks

Loic B.

**Comment by rajat974** [comment]
You can run the following commands 
`sudo apt update`
`sudo dpkg --remove --force-all pal && sudo apt autoremove`
`sudo apt install pal`

**Comment by LoicBoileau** [comment]
Update: It manged to go further than before (installing the tensors) but it still crashed, saying that python3.6 was not installed. The error message is the following : 
```
cp: cannot create regular file '/home/gaus/DreamVu/dreamvu_ws/lib/python3.6/site
-packages/': No such file or directory
dpkg: error processing package pal (--configure):
 installed pal package post-installation script subprocess returned error exit s
tatus 1
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.12) ...
Errors were encountered while processing:
 pal
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

And here's the full log : 
[install_pal.log](https://github.com/DreamVu/PAL-SDK/files/13417339/install_pal.log)

**Comment by LoicBoileau** [comment]
`Version: 5.1.1-b56`

**Comment by piyush-312** [comment]
Hi,
Can you please try the recommended jetpack version i.e. [JetPack 5.0.2](https://developer.nvidia.com/embedded/jetpack-sdk-502)
Let us know if you face any issue in doing so.

**Comment by LoicBoileau** [comment]
Hi, I have installed Jetpack 5.0.2 (i.e. 'Version: 5.0.2-b231'). However, I get the same error that of my first comment and by running the lines you gave it didn't fix it. Any idea what to do?

**Comment by LoicBoileau** [comment]
It worked! Thanks!
