### ISSUE TITLE
Initiating error with Pal camera (PAL::Init(camera_indexes)) with CMakeLists

### ISSUE THREAD

**Issue by LoicBoileau** [DreamVu/PAL-SDK#32]
Hi,

I'm back with an error generated by your PAL::init function. When I test on your code samples (compiling with .sh script) it works well; I can run your script 002_depth_panorama.cpp. However, when it is time to compile my program, with my CMakeLists, it compiles correctly but then crashes at PAL::Init(std::vector<int>(5)) with this error: `main: ./GET_URL.cpp:81: bool Init(): Assertion 'm_pModule != NULL' failed.`. I have joined my CMakeLists. 
[CMakeLists.txt](https://github.com/DreamVu/PAL-SDK/files/13711185/CMakeLists.txt)

Thanks alot for your help!

Loic B.

**Comment by piyush-312** [comment]
Hi @LoicBoileau,

Is it possible that you are running your program outside the dreamvu_ws python virtual environment?
If so then please activate the same using this command.

`source /home/$USER/DreamVu/dreamvu_ws/bin/activate
`

**Comment by LoicBoileau** [comment]
Your totally right, when making sure the python environment is activated everything works fine ! My mistake!

Small question tho: I cant find the savedpalproperties.txt, it says it should be inside explorer/ but i cant find it. Please let me know where i can find the pal properties file please! 

I appreciate it alot, thank you and have great holidays!

**Comment by piyush-312** [comment]
You can launch **Explorer** application and use the **Save** button to save the txt file. 
It will be saved in Explorer folder (~/DreamVu/PAL/Explorer/) by default.
