### ISSUE TITLE
question about PAL USB camera

### ISSUE THREAD

**Issue by jinxxo-j** [DreamVu/PAL-SDK#35]
I have a question.
On the DreamVu homepage, it says that only ROS melodic is supported for PAL USB products, but referring to this github page, it seems that ROS2 humble and foxy are also supported. Is ROS2 humble or foxy supported for PAL USB products?

**Comment by piyush-312** [comment]
Hi,

Yes we support the following configurations for PAL USB:

On Ubuntu 20.04 & Jetpack 5.0.2: **ROS2 foxy**
On Ubuntu 22.04: **ROS2 humble**

**Comment by jinxxo-j** [comment]
Thanks,

Best Regards.

Jinwoo Jang.

*Jinwoo Jang,*
*Computational Intelligence Laboratory,*
*School of Electrical and Electronic Engineering, Yonsei University*
*(https://cilab.yonsei.ac.kr/ <https://cilab.yonsei.ac.kr/>)*



2024년 3월 4일 (월) 오후 4:15, piyush-312 ***@***.***>님이 작성:
